name: crypto_test
description: A new Flutter project.

version: 1.4.1+41

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  get_it: ^7.6.0
  google_fonts: 6.1.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  web_socket_channel:
  candlesticks:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
