name: crypto_test
description: A new Flutter project.

version: 1.4.1+41

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.0
  dio: ^5.3.4
  flutter_screenutil: ^5.8.4
  get_it: ^7.6.0
  google_fonts: 6.1.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  logger: 2.0.2+1
  provider: ^6.1.1
  shimmer: ^3.0.0
  timeago: ^3.5.0
  url_launcher: ^6.2.1



flutter:
  uses-material-design: true
  assets:
    - assets/images/
